### ISSUE TITLE
Delete _site

### ISSUE THREAD

**Issue by MichaelCurrin** [vasilisa-the-beautiful/vasilisa#4]
You will get weird behavior locally if you add `_site`. It will make your repo appear like you have changes to commit.

The `_site` directory is like cache - it should be removed from the repo and added to `.gitignore`.

**Comment by vasilisa-the-beautiful** [comment]
Should I create a .gitignore1 folder and move it there? It automatically generates where it is, even if I delete it.

**Comment by MichaelCurrin** [comment]
Every time you run jekyll build or serve, `_site` will created (or updated) at the root. That is fine.

Even if you make a one line change in your code (like adding an item to navbar, that will affect _every_ page on your site which means a lot of noisy changes in `_site`.

So do this:

## Part 1

Make sure you have a text file called `.gitignore` with a dot at the start and add this row to it:

```
_site/
```

Then commit that file.

See my [demo ignore file](https://github.com/MichaelCurrin/jekyll-blog-demo/blob/master/.gitignore) which has more rows - you should add _all_ of those to your file.

## Part 2

Because you've already got `_site` known to git, you have to delete it this one time.

Dlete the entire `_site` directory locally. 

Then commit the change:

```sh
$ git add _site
$ git commit
$ git push
```

Now when you build, the `_site` directory will get created/update but git and GitHub won't care about it.

**Comment by MichaelCurrin** [comment]
Sorry this was a typo

```diff
-`.gitignore1.
+`.gitignore`.
```

**Comment by vasilisa-the-beautiful** [comment]
😄 Thought so. I think I fixed it.

**Comment by vasilisa-the-beautiful** [comment]
Thank you so much for all of your help Michael, I greatly appreciate it!
